### ISSUE TITLE
Like and dislike buttons in wrong place

### ISSUE THREAD

**Issue by PseudoDistant** [lightbeam24/CustomTube#150] opened 2024-01-09 16:26 UTC
OS: Arch Linux 64-bit (KDE Plasma 5.27.10)
Browser: Firefox 121.0
Extensions: Only CustomTube (I also had uBlock Origin and Return YouTube Dislike, disabling them didn't help.)
Using latest CustomTube
![image](https://github.com/lightbeam24/CustomTube/assets/67613281/2b3ce382-7174-4b37-a826-82041b32f648)

**Comment by lightbeam24** [comment] 2024-01-10 12:47
I can't reproduce this. Some experiment has probably rolled out to your account, so there's nothing I can do about this now.

**Comment by Bruh2801** [comment] 2024-01-14 20:18
> I can't reproduce this. Some experiment has probably rolled out to your account, so there's nothing I can do about this now.

wouldn't be surprised,was working nicely earlier,now this,and to add onto that for whatever goddamn reason the videos on the side just don't appear at all,definitely something youtube did

**Comment by ParkerGit2328** [comment] 2024-01-18 00:21
> OS: Arch Linux 64-bit (KDE Plasma 5.27.10) Browser: Firefox 121.0 Extensions: Only CustomTube (I also had uBlock Origin and Return YouTube Dislike, disabling them didn't help.) Using latest CustomTube ![image](https://private-user-images.githubusercontent.com/67613281/295270525-2b3ce382-7174-4b37-a826-82041b32f648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1Mzc1NzUsIm5iZiI6MTcwNTUzNzI3NSwicGF0aCI6Ii82NzYxMzI4MS8yOTUyNzA1MjUtMmIzY2UzODItNzE3NC00YjM3LWE4MjYtODIwNDFiMzJmNjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDAwMjExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MjVjM2I0ZjkyNGUzNDRkOGM5Yjk1MGYxMTkxZDI3NGVkNTg0YzYzOTVhMmNlYmE5ZDIyZDYzZTllNzkzMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4SJecOlrzrMVg51RZT3walQRE34OUGQTRyWJtrO1_5Y)

I had this bug too.

**Comment by ParkerGit2328** [comment] 2024-01-18 01:14
Will it be fixed in the next update?

**Comment by lightbeam24** [comment] 2024-01-18 01:20
Okay, I was just able to reproduce this. Annoyingly, it only happens on some accounts (even though there's literally no way to tell if you have the experiment without looking into the HTML). It's a one line fix, and it'll be fixed in the next update.

**Comment by ParkerGit2328** [comment] 2024-01-18 01:46
👍️

**Comment by lightbeam24** [comment] 2024-01-20 06:45
Alright, since it looks like the Chrome Web Store is gonna take a while to review 1.2.6, here is the CSS that fixes it:

```
html[watch-metadata-style^="hitchhiker"] #top-level-buttons-computed ytd-button-renderer,
html[watch-metadata-style^="hitchhiker"] #top-level-buttons-computed yt-button-view-model {
  order: var(--bt-wp-share-button-order);
  margin-right: var(--bt-wp-share-button-margin-right);
  margin-left: var(--bt-wp-share-button-margin-left);
}
```

You can put this into Stylus. Firefox users don't need to do this, as 1.2.6 was approved on addons.mozilla.org 2 days ago.

**Comment by lightbeam24** [comment] 2024-01-23 03:41
Should be fixed now.

**Closed by lightbeam24** 2024-01-23 03:41 UTC
