### ISSUE TITLE
[Question] Original Adobe flash player-like video player controls in 2012 layout?

### ISSUE THREAD

**Issue by Patricek0056** [lightbeam24/customtube#21] opened 2023-06-01 16:34 UTC
Hello, this is not an issue, but a question. It would be possible to tweak/change the YouTube player's CSS to have an old Adobe flash player-like controls in 2012 layout?

NO! I'm NOT saying, that “restore the Adobe flash plug-in!”, I'm saying only Adobe flash player-like video player controls. 

Thank you for understanding!

#### Screenshot with old Adobe flash player-like player controls:
![image](https://github.com/lightbeam24/customtube/assets/69351811/69607315-f790-4382-b68f-e5ffb79a5be6)

**Comment by Patricek0056** [comment] 2023-06-01 16:35
Sorry, but I didn't have been noticed about the “Discussions” tab in GitHub toolbar, but from now I will post the questions to “Discussions” instead.

**Comment by Patricek0056** [comment] 2023-06-01 16:40
By the way, the video timeline colour was also red.

**Comment by lightbeam24** [comment] 2023-06-01 16:52
This is a duplicate of issue #14.

**Closed by lightbeam24** 2023-06-01 16:52 UTC

**Comment by Patricek0056** [comment] 2023-06-01 16:54
Sorry, that I didn't have been noticed of that.
