### ISSUE TITLE
Multiple layout bugs in Mid 2013 YouTube layout

### ISSUE THREAD

**Issue by Aleksandra0056** [lightbeam24/CustomTube#135] opened 2023-11-27 06:07 UTC
## Description:
I discovered, that Mid 2013 YouTube layout has multiple layout bugs.

**UPDATE 28.11.2023:** Tested on Firefox only!

#### Home Screen:
- [ ] Empty button under "What to Watch" button
- [ ] Hovering over a video thumbnail on the home screen also shows a paid promo tooltip
- [ ] The live tooltip is unnecessarily stretched out due to a missing icon
- [ ] The premiere tooltip is unnecessarily stretched out due to a missing icon
- [ ] The "Show more" in the library section is misaligned to the separator
- [ ] The X button on the search bar is larger than before

#### Search screen:
- [ ] The "About these results" button isn't following old YouTube styles, and is misaligned to the separator
- [ ] The "Filters" button isn't following old YouTube styles and is misaligned to the separator

#### Watch page:
- [ ] Big gap between the About & Save button
- [ ] Expanded live chat isn't following the old YouTube styles
- [ ] Links are blinking when hovering at the description
- [x] Share button is showing the wrong text (_Won't fix_)
- [ ] The Autoplay button isn't fitting to old player style
- [ ] The "Enable Return YouTube Dislike compatibility" option isn't working correctly
- [ ] The "Join" button isn't following old YouTube styles
- [ ] The timeline slider on the player toolbar isn't stretched out correctly on screen with a 2560x1440 resolution

If one gets fixed, then I (or someone else) will mark it as completed.

#### Empty button under "What to Watch" button
![Empty button under What to Watch](https://github.com/lightbeam24/CustomTube/assets/69351811/97be0e6f-720a-4f3b-93f1-eb565c417b93)

--------------------

#### Hovering over a video thumbnail on the home screen also shows a paid promo tooltip
![Hovering over a video thumbnail in home screen](https://github.com/lightbeam24/CustomTube/assets/69351811/e7511bf1-192f-4bf7-a4e5-0f856564f604)

--------------------

#### The live tooltip is unnecessarily stretched out due to a missing icon
![Live tooltip is unnecessarily stretched out due to missing icon](https://github.com/lightbeam24/CustomTube/assets/69351811/40439d19-41f7-48a7-9fb4-b3e84f38658a)

--------------------

#### The premiere tooltip is unnecessarily stretched out due to a missing icon
![Premiere tooltip is unnecessarily stretched out due to missing icon](https://github.com/lightbeam24/CustomTube/assets/69351811/a1f3a20d-5148-4593-9661-a423e4db158e)

--------------------

#### The "Show more" in the library section is misaligned to the separator
![Show more in library section is misaligned to separator](https://github.com/lightbeam24/CustomTube/assets/69351811/184a79f2-8117-40b5-9383-78c52b5c4219)

--------------------

#### The X button on the search bar is larger than before
![The X button on search bar is larger than before](https://github.com/lightbeam24/CustomTube/assets/69351811/9f29df84-ec2f-4c20-92c4-29cc7f31d91f)

--------------------
--------------------

#### The "About these results" button isn't following old YouTube styles, and is misaligned to the separator
![The About these results button isn't following old YouTube styles, and is misaligned to separator](https://github.com/lightbeam24/CustomTube/assets/69351811/246b27a7-1932-4d13-a4c3-836c309f70ff)

--------------------

#### The "Filters" button isn't following old YouTube styles and is misaligned to the separator
![The filters button isn't following old YouTube styles, and is misaligned to separator](https://github.com/lightbeam24/CustomTube/assets/69351811/bc5e87e9-5878-4763-b1ea-ba2c19377452)

--------------------
--------------------

#### Big gap between the About & Save button
![Big gap between About   Save button](https://github.com/lightbeam24/CustomTube/assets/69351811/1b3fb875-c0e2-46d2-9fd8-e991ecefc394)

--------------------

#### Expanded live chat isn't following the old YouTube styles
![Expanded live chat isn't following the old YouTube styles](https://github.com/lightbeam24/CustomTube/assets/69351811/556eeb0b-027b-47e3-9d89-acc9abc94ea5)

--------------------

#### Links are blinking when hovering at the description

https://github.com/lightbeam24/CustomTube/assets/69351811/edbb045b-b3b4-494c-b2f2-f6dc401f7f85

#### The Autoplay button isn't fitting to old player style

![Autoplay button isn't fitting to old player style](https://github.com/lightbeam24/CustomTube/assets/69351811/724b5519-b630-4857-b422-c6082bd1c8b8)

--------------------

#### The "Enable Return YouTube Dislike compatibility" option isn't working correctly
![The ,Enable Return YouTube Dislike compatibility, option isn't working correctly](https://github.com/lightbeam24/CustomTube/assets/69351811/d93b231b-a59d-4aa2-9098-0976f45bf8fd)

--------------------

#### The "Join" button isn't following old YouTube styles
![The join button isn't following old YouTube styles](https://github.com/lightbeam24/CustomTube/assets/69351811/c01bd846-da2a-48cd-9eea-14521f7ce337)

--------------------

#### The timeline slider on the player toolbar isn't stretched out correctly on screen with a 2560x1440 resolution
![The timeline slider on player toolbar isn't stretched out correctly on 2560x1440 resolution](https://github.com/lightbeam24/CustomTube/assets/69351811/7d4fa906-a521-4954-a7c6-a42e151b278c)

--------------------
--------------------

### Won't fix:

> #### Share button is showing the wrong text
> ![Share button is showing wrong text](https://github.com/lightbeam24/CustomTube/assets/69351811/0169aefa-6334-443d-bcea-74f629bbbe65)

Sorry, my bad. That is probably intended to be a counter of shares

**Comment by uy813** [comment] 2023-11-28 14:18
hey you forgot about this one 
![unnamed](https://github.com/lightbeam24/CustomTube/assets/129725038/9335928c-a097-4174-9555-da3e2bcff2f4)

**Comment by lightbeam24** [comment] 2023-11-29 00:21
First of all: Layout inaccuracies != bugs.

> Empty button under "What to Watch" button

Cannot reproduce.

> Hovering over a video thumbnail on the home screen also shows a paid promo tooltip

Do not use CustomTube with Inline Playback enabled. You can turn it off here: https://www.youtube.com/account_playback

> The live tooltip is unnecessarily stretched out due to a missing icon
> The premiere tooltip is unnecessarily stretched out due to a missing icon

These are the same issue, but are very low priority.

> The X button on the search bar is larger than before

The X button didn't even exist in 2013, so in order to be the most accurate, it would need to be removed altogether, which I think would be a bad change.

> The "About these results" button isn't following old YouTube styles, and is misaligned to the separator
> The "Filters" button isn't following old YouTube styles and is misaligned to the separator
> Big gap between the About & Save button
> Expanded live chat isn't following the old YouTube styles

These are not bugs, and should not be reported here. Trust me, I am well aware of every tiny inaccuracy in this extension, it just takes time to fix them.

> The Autoplay button isn't fitting to old player style

Duplicate. Also not a bug.

> Links are blinking when hovering at the description

This is literally the intended result. Actually, the links are only supposed to be blue when hovering over the description. The fact that they're blue when you're NOT hovering over the description is the issue, but is an EXTREMELY low priority one.

> The "Enable Return YouTube Dislike compatibility" option isn't working correctly

Return YouTube Dislike itself does not work with an experiment that your account was flagged with.

> Sorry, my bad. That is probably intended to be a counter of shares

No, that is the dislike count. That is an issue with Return YouTube Dislike itself, due to the aforementioned experiment.

> The "Join" button isn't following old YouTube styles

There is an option to hide the Join button. (Maybe I should make it enabled by default)

> The timeline slider on the player toolbar isn't stretched out correctly on screen with a 2560x1440 resolution

It is **impossible** to make the progressbar full width while in fullscreen to my knowledge. It doesn't have anything to do with your resolution.

----

Sorry, but with only a couple of exceptions, these are all feature requests, not bugs. I'm not taking feature requests anymore, which I explained here: https://github.com/lightbeam24/CustomTube/discussions/121

As a result, I'm closing this issue.

**Closed by lightbeam24** 2023-11-29 00:21 UTC

**Comment by lightbeam24** [comment] 2023-11-29 00:22
> hey you forgot about this one ![unnamed](https://private-user-images.githubusercontent.com/129725038/286281721-9335928c-a097-4174-9555-da3e2bcff2f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTYxNjYsIm5iZiI6MTcwMTIxNTg2NiwicGF0aCI6Ii8xMjk3MjUwMzgvMjg2MjgxNzIxLTkzMzU5MjhjLWEwOTctNDE3NC05NTU1LWRhM2UyYmNmZjJmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQyMzU3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODZhZjBkYTQxMDhjZGQzMjhlNjU2YzAzOGJhMTg5MDM5MmZkYmJmNzQwNDkzMzIxYTc5NTkzNWRlYjJmNzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vN3wSfNmrWeVw3tZ5TJPETp3E4cF2k1rNAWG6CYt9w8)

You have an experiment that a few others have gotten. I don't know what experiment it is, so I can't reproduce nor fix that bug as of now.

**Comment by uy813** [comment] 2023-11-30 16:22
> > hey you forgot about this one ![unnamed](https://private-user-images.githubusercontent.com/129725038/286281721-9335928c-a097-4174-9555-da3e2bcff2f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTYxNjYsIm5iZiI6MTcwMTIxNTg2NiwicGF0aCI6Ii8xMjk3MjUwMzgvMjg2MjgxNzIxLTkzMzU5MjhjLWEwOTctNDE3NC05NTU1LWRhM2UyYmNmZjJmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQyMzU3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODZhZjBkYTQxMDhjZGQzMjhlNjU2YzAzOGJhMTg5MDM5MmZkYmJmNzQwNDkzMzIxYTc5NTkzNWRlYjJmNzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vN3wSfNmrWeVw3tZ5TJPETp3E4cF2k1rNAWG6CYt9w8)
> 
> You have an experiment that a few others have gotten. I don't know what experiment it is, so I can't reproduce nor fix that bug as of now.

you don't understand. this is a monitor display problem. i use chrome. my display is  1024 x 768. also did you reply my gmail suggestions?

**Comment by uy813** [comment] 2023-11-30 16:55
> > > hey you forgot about this one ![unnamed](https://private-user-images.githubusercontent.com/129725038/286281721-9335928c-a097-4174-9555-da3e2bcff2f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTYxNjYsIm5iZiI6MTcwMTIxNTg2NiwicGF0aCI6Ii8xMjk3MjUwMzgvMjg2MjgxNzIxLTkzMzU5MjhjLWEwOTctNDE3NC05NTU1LWRhM2UyYmNmZjJmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQyMzU3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODZhZjBkYTQxMDhjZGQzMjhlNjU2YzAzOGJhMTg5MDM5MmZkYmJmNzQwNDkzMzIxYTc5NTkzNWRlYjJmNzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vN3wSfNmrWeVw3tZ5TJPETp3E4cF2k1rNAWG6CYt9w8)
> > 
> > 
> > You have an experiment that a few others have gotten. I don't know what experiment it is, so I can't reproduce nor fix that bug as of now.
> 
> you don't understand. this is a monitor display problem. i use chrome. my display is 1024 x 768. also did you reply my gmail suggestions?

hold on. when i switched to my alt channel, it looks like it has been fixed. but when i go back to my main channel, it's not fixed! what the hell is going on?

**Comment by lightbeam24** [comment] 2023-12-02 14:41
> also did you reply my gmail suggestions?

I don't check that email often. I only created it because the Chrome Web Store requires that you have a contact email.

> hold on. when i switched to my alt channel, it looks like it has been fixed. but when i go back to my main channel, it's not fixed! what the hell is going on?

I already told you, one of your accounts has an experiment that's doing that.
