### ISSUE TITLE
Like/dislike button bad position

### ISSUE THREAD

**Issue by portex7000** [lightbeam24/CustomTube#155] opened 2024-01-19 08:04 UTC
I was watching video, and i wanted to like. I realized that like and dislike button were on left instead of right
![image](https://github.com/lightbeam24/CustomTube/assets/150171265/2725f6be-ee95-49fb-babd-c0b16add33ab)

**Comment by lightbeam24** [comment] 2024-01-19 11:51
Does this happen on Firefox? 1.2.6 is already out on Firefox and fixed a similar issue, but is still pending review on the Chrome Web Store (taking longer than usual).

**Comment by portex7000** [comment] 2024-01-20 06:48
No, it doesn't happen on firefox, but the like button is not displayed correctly
![image](https://github.com/lightbeam24/CustomTube/assets/150171265/2d0b9d67-f545-47ed-aeb6-f5626612fcd0)

**Comment by lightbeam24** [comment] 2024-01-20 06:49
Oh right I still have to look into that. Are you using YouTube signed out by any chance?

**Comment by portex7000** [comment] 2024-01-20 06:50
On firefox, i was signed out. On google, i use my account

**Comment by lightbeam24** [comment] 2024-01-20 13:26
Yeah, it looks like it's caused by being signed out. I'll fix it in the next update.

**Comment by lightbeam24** [comment] 2024-01-26 17:02
Both issues are fixed now.

**Closed by lightbeam24** 2024-01-26 17:02 UTC
