### ISSUE TITLE
Save and Share buttons are oddly placed (on Firefox, using the 2016 layout but it's also broke on 2017)

### ISSUE THREAD

**Issue by ItsRoachinTime** [lightbeam24/CustomTube#146] opened 2023-12-09 01:57 UTC
![image](https://github.com/lightbeam24/CustomTube/assets/133606138/f1bf7630-966d-4e9a-bcea-fe9392b0f711)

I don't know what's causing this, i've made sure to turn off any not confirmed compatible extensions and scripts and it still has this issue

**Comment by ItsRoachinTime** [comment] 2023-12-09 02:36
also side note, i've discovered the number count on the Share button is actually the dislike count from BBYD, after disabling it the text reverted back to Share

**Comment by lightbeam24** [comment] 2024-01-17 22:23
Does this still happen? Sorry for the late response.

**Comment by ItsRoachinTime** [comment] 2024-01-18 03:13
> Does this still happen? Sorry for the late response.

**
![image](https://github.com/lightbeam24/CustomTube/assets/133606138/643cf3b4-45d3-4276-9f06-a5ca947a7838)
**

yeah it still happens unfortunatley

**Comment by lightbeam24** [comment] 2024-01-18 03:15
Okay so this is a duplicate of another issue that will be fixed in the next update.

**Closed by lightbeam24** 2024-01-18 03:15 UTC
