### ISSUE TITLE
Play/Pause is delayed when using 2019 layout

### ISSUE THREAD

**Issue by dp-zini** [lightbeam24/CustomTube#30] opened 2023-06-27 00:14 UTC
Clicking on the video pauses after a couple seconds of delay, pressing the button pauses instantly and pressing space/k pauses instantly but there is a delay to when the pause icon appears on screen.

This doesn't happen on the 2017 layout but that layout looks very strange with dark mode enabled and I'd prefer to use the polymer layout.

**Comment by lightbeam24** [comment] 2023-06-27 00:27
I'll look into it. As for dark mode, it is only partially supported at the moment. I plan to fix that eventually.

**Comment by Chalenor** [comment] 2023-06-27 18:41
To add detail to this, it's both the 2019 and 2017 layouts for me, and it only occurs after I've been watching a video for about 30 minutes. It feels like a lag that builds over time from high resource usage and can take up to more than a second for the video to pause if the player is clicked rather than using the pause button.

Refreshing the page makes it go away for another 30 minutes or so until the lag creeps back in enough to be troublesome again.

**Comment by lightbeam24** [comment] 2023-06-27 19:45
I think I know what the issue is. I'll probably make a version 1.0.4.2 to fix this.

**Comment by lightbeam24** [comment] 2023-06-28 21:04
Should be fixed, or at least mitigated in version 1.0.4.2. It doesn't seem to happen to me anymore. Though I didn't test 1.0.4.2 for very long, since I'm more focused on testing the next real version (1.1.0).

**Comment by lightbeam24** [comment] 2023-08-16 02:09
Assuming it's fixed unless proven otherwise.

**Closed by lightbeam24** 2023-08-16 02:09 UTC
